const scheduleData = [
  {
    area: "Marketing",
    nombre: "Ecuador - Machala",
    oficina: "Ecuador",
    inicio: "09:00",
    fin: "18:00",
    breakInicio: "14:00",
    breakFin: "15:00",
  },
  {
    area: "Contabilidad",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "Contabilidad",
    nombre: "Colombia - Bogotá",
    oficina: "Colombia",
    inicio: "08:00",
    fin: "18:30",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "Contabilidad",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "10:00",
    fin: "18:15",
    breakInicio: "14:00",
    breakFin: "14:30",
  },
  {
    area: "Ventas",
    nombre: "Colombia - Bogotá",
    oficina: "Colombia",
    inicio: "08:00",
    fin: "18:30",
    breakInicio: "14:00",
    breakFin: "16:00",
  },
  {
    area: "Ventas",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "10:00",
    fin: "20:30",
    breakInicio: "14:00",
    breakFin: "15:30",
  },
  {
    area: "Ventas",
    nombre: "México - DF",
    oficina: "Mejico",
    inicio: "10:00",
    fin: "19:00",
    breakInicio: "14:00",
    breakFin: "16:00",
  },
  {
    area: "Ventas",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "10:00",
    fin: "20:45",
    breakInicio: "14:00",
    breakFin: "17:00",
  },
  {
    area: "Comunicación",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "12:00",
    breakFin: "13:00",
  },
  {
    area: "Recursos Humanos",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "Recursos Humanos",
    nombre: "Argentina - Ushuaia",
    oficina: "Ushuaia",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "Coordinación",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "10:00",
    fin: "19:00",
    breakInicio: "14:30",
    breakFin: "15:30",
  },
  {
    area: "Coordinación",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "10:00",
    fin: "20:15",
    breakInicio: "14:00",
    breakFin: "16:30",
  },
  {
    area: "Gestión",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "10:00",
    fin: "19:00",
    breakInicio: "14:30",
    breakFin: "15:30",
  },
  {
    area: "Gestión",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "10:00",
    fin: "20:15",
    breakInicio: "14:00",
    breakFin: "16:30",
  },
  {
    area: "Gestión",
    nombre: "Argentina - Ushuaia",
    oficina: "Ushuaia",
    inicio: "07:00",
    fin: "17:00",
    breakInicio: "14:00",
    breakFin: "14:45",
  },
  {
    area: "Marketing",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "Marketing",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "10:00",
    fin: "18:15",
    breakInicio: "14:00",
    breakFin: "14:30",
  },
  {
    area: "Marketing",
    nombre: "México - DF",
    oficina: "Mejico",
    inicio: "06:00",
    fin: "15:30",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "Project-Manager",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "Project-Manager",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "10:00",
    fin: "18:15",
    breakInicio: "14:00",
    breakFin: "14:30",
  },
  {
    area: "Community Manager",
    nombre: "Chile - Santiago",
    oficina: "Chile",
    inicio: "8:00",
    fin: "18:30",
    breakInicio: "13:00",
    breakFin: "14:30",
  },
  {
    area: "Community Manager",
    nombre: "Colombia - Medellin",
    oficina: "Colombia",
    inicio: "8:00",
    fin: "17:00",
    breakInicio: "16:00",
    breakFin: "17:00",
  },
  {
    area: "Community Manager",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "10:00",
    fin: "18:15",
    breakInicio: "14:00",
    breakFin: "14:30",
  },
  {
    area: "Community Manager",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
];

export default scheduleData;
