const scheduleData = [
  {
    area: "Marketing",
    nombre: "Ecuador - Machala",
    oficina: "Ecuador",
    inicio: "09:00",
    fin: "18:00",
    breakInicio: "14:00",
    breakFin: "15:00",
  },

  {
    area: "Contabilidad",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "13:30",
    breakFin: "14:30",
  },
  // {
  //   area: "Contabilidad",
  //   nombre: "Colombia - Bogotá",
  //   oficina: "Colombia",
  //   inicio: "08:00",
  //   fin: "18:30",
  //   breakInicio: "13:00",
  //   breakFin: "14:00",
  // },
  {
    area: "Contabilidad",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "10:00",
    fin: "18:15",
    breakInicio: "14:00",
    breakFin: "14:30",
  },
  {
    area: "Ventas",
    nombre: "Colombia - Bogotá",
    oficina: "Colombia",
    inicio: "08:00",
    fin: "18:30",
    breakInicio: "13:00",
    breakFin: "14:30",
  },
  {
    area: "Ventas",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "10:00",
    fin: "20:30",
    breakInicio: "14:00",
    breakFin: "15:30",
  },
  {
    area: "Ventas",
    nombre: "México - CDMX",
    oficina: "Mejico",
    inicio: "09:00",
    fin: "19:00",
    breakInicio: "14:00",
    breakFin: "16:00",
  },
  {
    area: "Ventas",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "9:30",
    fin: "19:00",
    breakInicio: "14:00",
    breakFin: "15:30",
    iniciov: "10.00",
    finv: "19.00",
    breakIniciov: "14.00",
    breakFinv: "16.00",
  },

  {
    area: "Coordinación",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "10:00",
    fin: "19:00",
    breakInicio: "14:30",
    breakFin: "15:30",
  },
  {
    area: "Coordinación",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "9:30",
    fin: "19:00",
    breakInicio: "14:00",
    breakFin: "15:30",
    iniciov: "10.00",
    finv: "19.00",
    breakIniciov: "14.00",
    breakFinv: "16.00",
  },
  {
    area: "Gestión",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "10:00",
    fin: "19:00",
    breakInicio: "14:30",
    breakFin: "15:30",
  },
  {
    area: "Gestión",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "9:30",
    fin: "19:00",
    breakInicio: "14:00",
    breakFin: "15:30",
    iniciov: "10.00",
    finv: "19.00",
    breakIniciov: "14.00",
    breakFinv: "16.00",
  },
  {
    area: "Gestión",
    nombre: "Argentina - Ushuaia",
    oficina: "Ushuaia",
    inicio: "07:00",
    fin: "17:00",
    breakInicio: "14:00",
    breakFin: "14:45",
  },
  {
    area: "Marketing",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "07:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "Marketing",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "10:00",
    fin: "18:15",
    breakInicio: "14:00",
    breakFin: "14:30",
  },
  {
    area: "Marketing",
    nombre: "México - CDMX",
    oficina: "Mejico",
    inicio: "06:00",
    fin: "15:30",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "Project-Manager",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "Project-Manager",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "10:00",
    fin: "18:15",
    breakInicio: "14:00",
    breakFin: "14:30",
  },
  {
    area: "Project-Manager",
    nombre: "Colombia - Bogotá",
    oficina: "Colombia",
    inicio: "08:00",
    fin: "18:30",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "Community Manager",
    nombre: "Chile - Santiago",
    oficina: "Chile",
    inicio: "8:00",
    fin: "18:30",
    breakInicio: "13:00",
    breakFin: "14:30",
  },
  {
    area: "Community Manager",
    nombre: "Colombia - Medellin",
    oficina: "Colombia",
    inicio: "8:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "Community Manager",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "10:00",
    fin: "18:15",
    breakInicio: "14:00",
    breakFin: "14:30",
  },
  {
    area: "Community Manager",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "Data Entry",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "12:00",
    breakFin: "13:00",
  },
  {
    area: "Comunicación",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "14:00",
    breakFin: "15:00",
  },
  {
    area: "RRHH-Profesionales",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "RRHH-Seleccion",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "RRHH-interno",
    nombre: "Argentina - Córdoba",
    oficina: "Córdoba",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "14:00",
  },
  {
    area: "RRHH-interno",
    nombre: "España - Elche",
    oficina: "España",
    inicio: "10:00",
    fin: "18:15",
    breakInicio: "14:00",
    breakFin: "14:30",
    iniciov: "10.00",
    finv: "18.30",
    breakIniciov: "14.00",
    breakFinv: "14.30",
  },

  {
    area: "RRHH-Profesionales",
    nombre: "Argentina - Ushuaia",
    oficina: "Ushuaia",
    inicio: "08:00",
    fin: "17:00",
    breakInicio: "13:00",
    breakFin: "13.15",
  },
];

export default scheduleData;
